# -*- mode: ruby -*-
# vi: set ft=ruby :

def clean_utf8_string(input)
  input.encode('UTF-16', 'UTF-8', invalid: :replace, replace: '').encode('UTF-8')
end

Vagrant.configure("2") do |config|
  # Configuration principale
  config.vm.box = "centos/7"

  # Obtenir l'adresse IPv4 actuelle sur Windows
  if RbConfig::CONFIG['host_os'] =~ /mswin|mingw|cygwin/
    ipconfig_result = `ipconfig /all`
    cleaned_ipconfig_result = clean_utf8_string(ipconfig_result)
    #puts "ipconfig_result: #{cleaned_ipconfig_result.inspect}"  # Sortie de débogage

    # Utiliser une expression régulière pour extraire l'adresse IPv4
    current_ip_match = cleaned_ipconfig_result.match(/Adresse IPv4[^\d]*(\d+\.\d+\.\d+\.\d+)/)
    current_ip = current_ip_match[1].strip if current_ip_match
  else
    # Sur les systèmes Unix-like, utilisez une autre méthode pour obtenir l'adresse IPv4
    current_ip = `hostname -I | awk '{print $1}'`.strip
  end

  if current_ip.nil? || current_ip.empty?
    raise "Impossible de récupérer l'adresse IP."
  end
  puts "l'adresse ip générée ets : #{current_ip}" 
  # Utiliser l'adresse IP dans la configuration Vagrant
  config.vm.network "public_network", ip: current_ip

  # Configuration spécifique au fournisseur VirtualBox
  config.vm.provider "virtualbox" do |vb|
    # Paramètres de la machine virtuelle VirtualBox
    # vb.gui = true
    vb.memory = "5000"
    vb.cpus = "2"
  end

  # Configuration de la provision avec un script shell
  config.vm.provision "shell", inline: <<-SHELL
    sudo yum update
    sudo yum install gedit
  SHELL
end
